In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [2]:
x = np.arange(0,100)
y = np.arange(0,100)

In [3]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Repare que x e y são ARRAYS UNIDIMENSIONAIS!

In [5]:
lr = LinearRegression()

In [6]:
lr.fit(x, y)

ValueError: ignored

Repare que se eu eu tentar treinar o modelo com um array unidimensional aparece um erro: "Expected 2D array, got 1D array instead"

In [7]:
x.shape

(100,)

In [8]:
y.shape

(100,)

In [9]:
# Ao passar o -1 estou dizendo para o reshape que quero deixar aquele axis imutável
# Ao passar o 1 estou dizendo que quero criar outra dimensao, nesse caso com 1 coluna apenas
x = x.reshape(-1,1)

In [10]:
x.shape

(100, 1)

In [11]:
# Repare que agora o treino do modelo irá funcionar
# Só preciso converter para 2D os atributos preditores
lr.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Outros exemplos de reshape

In [15]:
a = np.array([[1,2,3], [4,5,6]])

In [16]:
a.shape

(2, 3)

In [20]:
a.size

6

OBS IMPORTANTE.: O RESHAPE DEVE SER FEITO OBEDECENDO O TAMANHO DO ARRAY.
O TAMANHO DO ARRAY É DADO PELA FORMULA Nº DE LINHAS X Nº DE COLUNAS

In [24]:
# O primeiro argumento é o numero de linhas o segundo é numero de colunas
a = a.reshape(3,2)

In [25]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
a.shape

(3, 2)

In [27]:
b = np.array([1,0,1,1,0,1,1])
b

array([1, 0, 1, 1, 0, 1, 1])

In [28]:
b.shape

(7,)

In [29]:
b.size

7

In [32]:
b.reshape(-1,1)

array([[1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1]])